Header header

float64 des_v_x
float64 des_v_y
float64 des_v_z

float64 fb_a_x
float64 fb_a_y
float64 fb_a_z

float64 des_a_x
float64 des_a_y
float64 des_a_z

float64 des_q_x
float64 des_q_y
float64 des_q_z
float64 des_q_w

float64 des_thr
float64 hover_percentage
float64 thr_scale_compensate
float64 voltage

float64 exec_err_axisang_x
float64 exec_err_axisang_y
float64 exec_err_axisang_z
float64 exec_err_axisang_ang

float64 fb_axisang_x
float64 fb_axisang_y
float64 fb_axisang_z
float64 fb_axisang_ang

float64 fb_rate_x
float64 fb_rate_y
float64 fb_rate_z

float64 des_q_roll
float64 des_q_pitch
float64 des_q_yaw

float64 des_br_roll
float64 des_br_pitch
float64 des_br_yaw

float64 u_br_roll
float64 u_br_pitch
float64 u_br_yaw

float64 fb_br_roll
float64 fb_br_pitch
float64 fb_br_yaw

float64 fb_torque_roll
float64 fb_torque_pitch
float64 fb_torque_yaw
float64 final_thr

float64[4] motors_thrust 

nav_msgs/Odometry end_pose_ref

float64 l1_res_x
float64 l1_res_y
float64 l1_res_z
float64 l1_dhat_x
float64 l1_dhat_y
float64 l1_dhat_z
float64 l1_dhatf_x
float64 l1_dhatf_y
float64 l1_dhatf_z
float64 des_a_l1_x
float64 des_a_l1_y
float64 des_a_l1_z

float64 a_lpf_x
float64 a_lpf_y
float64 a_lpf_z

float64[] delta_theta