seed: 11
update_freq: 5.0
resolution: 0.05

# map size unit meter
x_length: 5
y_length: 5
z_length: 1
# whether to generate ground and ceil
ground: 0
ceil: 0

# # 1: perlin noise 3D
# param: complexity
# # large value will be complex
# # typical 0.0 ~ 0.5 
# 越低连续性越高
# param: fill
# # infill persentage
# # typical: 0.4 ~ 0.0
# param: fractal
# # large value will have more detail
# param: attenuation
# # for fractal attenuation
# # typical: 0.0 ~ 0.5

# 质点模型
# type: 1
# complexity: 0.017
# fill: 0.001
# fractal: 1
# attenuation: 0.3

# 2: perlin box random map
# type: 2
# width_min: 1.0
# width_max: 1.5
# height_min: 2.5
# height_max: 3.0
# obstacle_number: 30

# 5: custom map
# type: 5
# box0_size_x: 1.0
# box0_size_y: 0.6
# box0_size_z: 1.5

# 3: 2d maze still developing
#!
# type: 3
# road_width: 1.5
# add_wall_x: 1
# add_wall_y: 0
# maze_type: 1

# # 4: maze 3d
# numNodes: 40
# connectivity: 0.8
# nodeRad: 1
# roadRad: 10

# 6: clutter map
type: 6
obs_num: 1
min_len: 1
max_len: 2
min_wid: 0.11
max_wid: 0.16

# 7: one_pt
# type: 7
# pt_x: 1
# pt_y: 0
# pt_z: 1.0